# Generated by Django 3.2.16 on 2023-07-20 10:44

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20230720_1342'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='post',
            name='unique_following',
        ),
        migrations.RemoveConstraint(
            model_name='post',
            name='check_self_follow',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='unique_following'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('user', django.db.models.expressions.F('following')), _negated=True), name='check_self_follow'),
        ),
    ]
